runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: src/index.html
  upload: src/index.html

- url: /(.*)
  static_files: src/\1
  upload: src/(.*)

skip_files:
- ^node_modules/(?!node\.js$).*node_modules